version: "3.9"
services:
  django-app-service:
    build: ./python_app/
    container_name: django-app-container
    volumes:
      - /home/ubuntu/test_pipeline/Project_Pipeline/python_app:/app/ 
    
    ports:
      - 8000:8000
    
    networks:
      - djano_pipe

  nginx_service:
    build: ./nginx_conf/
    container_name: nginx_cont
    ports:
      - 8001:8001
    
    networks:
      - djano_pipe

networks:
  djano_pipe:
