version: "3.9"
services:
  djano-app-container:
    build: ./python_app/
    container_name: djano-app-container
    volumes:
      - /var/lib/jenkins/workspace/Django_Pipeline/python_app:/app/ 
    
    networks:
      - djano_pipe

  nginx:
    build: ./nginx_conf/
    container_name: nginx_cont
    depands_on: djano-app-container
    ports:
      - 80:80
    
    networks:
      - djano_pipe

networks:
  djano_pipe:
